# Generated by Django 6.1 on 2026-08-20 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(verbose_name='fecha de devolución')),
                ('kilometraje_inicial', models.PositiveIntegerField(default=0)),
                ('kilometraje_final', models.PositiveIntegerField()),
                ('nivel_combustible', models.CharField(choices=[('VACIO', 'Vacío'), ('UN_CUARTO', '1/4'), ('MEDIO', '1/2'), ('TRES_CUARTOS', '3/4'), ('LLENO', 'Lleno')], default='LLENO', max_length=14, verbose_name='nivel de combustible')),
                ('danos', models.TextField(blank=True, verbose_name='daños observados')),
                ('cargo_adicional', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='cargo adicional (CLP)')),
                ('dias_atraso', models.PositiveIntegerField(default=0, verbose_name='días de atraso')),
                ('estado_vehiculo_resultante', models.CharField(max_length=14)),
                ('registrada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'devolución',
                'verbose_name_plural': 'devoluciones',
                'ordering': ['-registrada_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='monto (CLP)')),
                ('medio', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Tarjeta de débito'), ('CREDITO', 'Tarjeta de crédito'), ('TRANSFERENCIA', 'Transferencia')], max_length=14)),
                ('estado', models.CharField(choices=[('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PAGADO', max_length=8)),
                ('comprobante', models.CharField(blank=True, max_length=40)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de término')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('monto_estimado', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='monto estimado (CLP)')),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
