# Generated by Django 6.1 on 2026-08-20 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980)], verbose_name='año')),
                ('categoria', models.CharField(choices=[('CITYCAR', 'City car'), ('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('CAMIONETA', 'Camioneta'), ('FURGON', 'Furgón')], max_length=12)),
                ('transmision', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=12, verbose_name='transmisión')),
                ('combustible', models.CharField(choices=[('BENCINA', 'Bencina'), ('DIESEL', 'Diésel'), ('HIBRIDO', 'Híbrido'), ('ELECTRICO', 'Eléctrico')], default='BENCINA', max_length=12)),
                ('tarifa_diaria', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tarifa diaria (CLP)')),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ARRENDADO', 'Arrendado'), ('MANTENIMIENTO', 'En mantenimiento'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', max_length=14)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['marca', 'modelo', 'patente'],
            },
        ),
    ]
